name: gab
version: '1.0'
summary: A webapp for Gab.com
description: |
  A webapp for Gab.com
  
license: MIT

assumes:
  - command-chain
  
base: core20
grade: stable
confinement: strict

apps:
  gab:
    command: launch
    command-chain: 
      - bin/homeishome-launch
    extensions:
      - gnome-3-38      
    plugs:
      - network
      - opengl
      - audio-playback
      - browser-support
      - home
      - desktop
      - desktop-legacy
      - x11
      - wayland
      - alsa
      - pulseaudio      
      
parts:
  gab:
    plugin: dump
    source: scripts
    build-snaps:
      - nativefier
    stage-snaps:
      - nativefier
      
    stage-packages:
      - libnss3
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libcairo-5c0
      
  homeishome-launch:
    plugin: nil
    stage-snaps:
      - homeishome-launch
      
  cleanup:
    plugin: nil
    build-snaps: 
      - core20
      - gnome-3-38-2004
    override-prime: |
      set -eux
      for snap in "core20" "gnome-3-38-2004"; do  # List all content-snaps and base snaps you're using here
        cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done
