name: gab
version: '1.0'
summary: A webapp for Gab.com
description: |
  A webapp for Gab.com
  
license: MIT

assumes:
  - command-chain
  
base: core20
grade: stable
confinement: strict

apps:
  gab:
    command: launch
    command-chain: 
      - bin/homeishome-launch
    plugs:
      - network
      - home
      
parts:
  gab:
    plugin: dump
    source: scripts
    after: 
      - nativefier
    
  nativefier:
    source: https://github.com/gfpacheco/Nativefier
    plugin: npm
    npm-node-version: latest
    
  homeishome-launch:
    plugin: nil
    stage-snaps:
      - homeishome-launch
