name: gab
version: '1.0'
summary: A webapp for Gab.com
description: |
  A webapp for Gab.com
  
license: MIT

assumes:
  - command-chain
  
base: core20
grade: stable
confinement: strict

apps:
  gab:
    command: launch
    command-chain: 
      - bin/homeishome-launch
    plugs:
      - network
      - home
      
parts:
  gab:
    plugin: dump
    source: scripts
    after: 
      - nativefier
    
  nativefier:
    plugin: npm
    npm-node-version: "16.13.2"
    source: https://github.com/nativefier/nativefier.git
    source-type: git
    build-environment:
      - npm_config_global: 'true'
    
    build-packages:
      - git
      - npm
    
  homeishome-launch:
    plugin: nil
    stage-snaps:
      - homeishome-launch
